server:
  port: 9092

logging:
  level:
    org.zalando.logbook: trace

spring:
  main:
    allow-bean-definition-overriding: true
        
keycloak:
  realm: oose
  auth-server-url: https://localhost:8443/auth
  resource: dataserver
  principal-attribute: preferred_username
  bearer-only: true

  # development only
  allow-any-hostname: true
  disable-trust-manager: true
  