server:
  port: 9090
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
    
spring:
  main:
    allow-bean-definition-overriding: true
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    
zuul:  
  sensitive-headers: Cookie,Set-Cookie
  routes:    
    resource:      
      path: /api/resource/**
      url: http://localhost:9091/resource
      
 
keycloak:
  auth-server-url: https://localhost:8443/auth
  realm: openoose
  resource: gateway
  principal-attribute: preferred_username
  credentials:
    secret: 31d77b02-97e9-4e7c-9b83-e4c141780ba7
  
  

# development only
  allow-any-hostname: true
  disable-trust-manager: true

      
      



