server:
  port: 9090
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    keyAlias: tomcat
    
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://localhost:8443/auth/realms/oose/protocol/openid-connect/token
            authorization-uri: https://localhost:8443/auth/realms/oose/protocol/openid-connect/auth
            user-info-uri: https://localhost:8443/auth/realms/oose/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: 31d77b02-97e9-4e7c-9b83-e4c141780ba7
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
      - id: resource
        uri: http://localhost:9091
        predicates:
          - Path=/api/resource/**
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/api/(?<remaining>.*), /$\{remaining}

