server:
  port: 9090
#  ssl:
#    key-store: keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
    
spring:
  main:
    allow-bean-definition-overriding: true
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    
zuul:  
  routes:    
    resource:      
      path: /api/resource/**
      url: http://localhost:9091/resource
  sensitive-headers: Authorization,Cookie,Set-Cookie
  sslHostnameValidationEnabled: false
  
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: openoose
  resource: gateway
  principal-attribute: preferred_username
  public-client: true
      
#ribbon:
#  IsSecure: true
      
#rest.security.issuer-uri: http://localhost:8080/auth/realms/openoose
  
#security:
#  oauth2:
#    client:
#      access-token-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token
#      user-authorization-uri: ${rest.security.issuer-uri}/protocol/openid-connect/auth
#      client-id: gateway
#      client-secret: 32a5cc5e-3b21-4853-92a3-5da43304d76d
#    resource:
#      user-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/userinfo
#      prefer-token-info: false
          
      



