server:
  port: 9091
#  ssl:
#    key-store: keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat

logging:
  level:
    org.zalando.logbook: trace

spring:
  main:
    allow-bean-definition-overriding: true
        
keycloak:
  realm: openoose
  auth-server-url: http://localhost:8080/auth 
  resource: gateway
  principal-attribute: preferred_username
  bearer-only: true
